language: java

jdk:
  - oraclejdk8

install: mvn install -q -DskipTests=true


services:
  - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

script: mvn test -q
